version: '3.7'
volumes:
    hivedb: {}
    coordinatordb: {}
    workerdb: {}
    supersetdb: {}
services:
    postgres:
      image: postgres:9.4
      container_name: postgres
      environment:
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
          - POSTGRES_DB=postgres
      volumes:
        - hivedb:/var/lib/postgresql/data
        - ./postgres/scripts:/docker-entrypoint-initdb.d/
      ports:
        - "5432:5432"
      networks:
        ntrino:
          aliases:
            - postgres
      healthcheck:
          test: ["CMD-SHELL", "pg_isready -U postgres"]
          interval: "20s"
          timeout: "20s"
          retries: 3

    hive:
      image: cloudnativek8s/apache-hive:3.1.3-v1.0.0
      #build: hive/
      container_name: hive
      environment:
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        - AWS_ACCESS_KEY=${AWS_ACCESS_KEY}
        - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      volumes:
        - ./hive/conf/hive-site.xml:/opt/app/apache-hive-3.1.3-bin/conf/hive-site.xml
        - ./hive/data:/tmp/hive
        #copy output data directory from https://github.com/skhatri/spark-delta-by-example project
        - ./hive/output:/opt/data/output
      ports:
        - "10000:10000"
        - "9083:9083"
      networks:
        ntrino:
          aliases:
            - hive
      depends_on:
        postgres:
          condition: service_healthy

    coordinator:
      build: .
      #image: trinodb/trino:418
      container_name: coordinator
      environment:
        - AWS_ACCESS_KEY=${AWS_ACCESS_KEY}
        - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      ports:
        - "8080:8080"
        - "8443:8443"
      expose:
        - "8080"
        - "8443"
      volumes:
        - coordinatordb:/data/trino
        - ./coordinator:/etc/trino
        - ./security:/opt/trino/security
        - ./certs:/opt/trino/certs
        - ./hive/output:/opt/data/output
      networks:
        ntrino:
          aliases:
            - coordinator
      depends_on:
        postgres:
            condition: service_healthy
      healthcheck:
          test: ["CMD-SHELL", "curl -sS http://localhost:8080/|| exit 1"]
          interval: "20s"
          timeout: "20s"
          retries: 3


    worker-1:
      image: trinodb/trino:418
      container_name: worker-1
      environment:
        - AWS_ACCESS_KEY=${AWS_ACCESS_KEY}
        - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      ports:
        - "8090:8080"
        - "9443:8443"
      volumes:
        - workerdb:/data/trino
        - ./worker:/etc/trino
        - ./certs:/opt/trino/certs
        - ./hive/output:/opt/data/output
      networks:
        ntrino:
          aliases:
            - worker-1
      depends_on:
        coordinator:
          condition: service_healthy

    superset:
      build: superset
      container_name: superset
      environment:
        - DATA_DIR=/opt/superset/data
        - MAPBOX_API_KEY=${MAPBOX_API_KEY}
        - SUPERSET_SECRET_KEY=HAjeudha2uahde*$Hau&@1
      volumes:
      - ./certs:/opt/superset/certs
      - supersetdb:/opt/superset/data
      ports:
        - "9000:8088"
      networks:
        ntrino:
          aliases:
            - superset
      depends_on:
        coordinator:
          condition: service_healthy
        postgres:
          condition: service_healthy


    trino-proxy:
      image: "envoyproxy/envoy-dev:latest"
      command: /usr/local/bin/envoy -c /etc/trino-envoy.yaml --service-cluster trino_coordinator -l debug
      container_name: "trino-proxy"
      volumes:
        - ./envoy/trino-envoy.yaml:/etc/trino-envoy.yaml
        - ./certs/:/opt/certs
      networks:
        ntrino:
          aliases:
            - trino-proxy
      expose:
        - "8453"
        - "8001"
      ports:
        - "8453:8453"
        - "8001:8001"


networks:
  ntrino: {}

      
